### ISSUE TITLE
Category : url 수정

### ISSUE THREAD

**Issue by yoo2wo** [HONGVELOPER/NHN-project#2]
product와 url 중복으로 인한 수정
- 수정 전
<img width="934" alt="스크린샷 2022-07-25 오후 5 39 29" src="https://user-images.githubusercontent.com/51395712/180735136-e93d15ec-db9f-4b3f-a529-90f548473d80.png">
- 수정 후
<img width="938" alt="스크린샷 2022-07-25 오후 5 40 34" src="https://user-images.githubusercontent.com/51395712/180735382-4fd3cd1d-c001-4c1e-968e-ccd292586ea4.png">

**Comment by HONGVELOPER** [comment]
확인했습니다!
